my_geonode/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2017 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import url, include
from django.views.generic import TemplateView

from geonode.urls import urlpatterns

urlpatterns += [
## include your urls here
url(r'^polls/', include('polls.urls')),
]

urlpatterns = [
   url(r'^/?$',
       TemplateView.as_view(template_name='site_index.html'),
       name='home'),
 ] + urlpatterns

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

my_geonode/templates/footer.html
      <div class="footer">
          <div class="row">
            <div class="col-md-1 col-md-offset-1" >
            <img class="footer_img" src="static/img/Government-of-Tanzania-Logo.png">
            </div>
            <div class="col-md-1">
            <img class="footer_img" src="static/img/UKaid-Logo.png">
            </div>
            <div class="col-md-1">
             <img class="footer_img1" src="static/img/The-World-Bank-logo.png">

            </div>
            <div class="col-md-1">
             <img class="footer_img" src="static/img/TURP-Logo.png">

            </div>

            <div class="col-md-1">
            <img class="footer_img" src="static/img/ARU-logo.jpg">

            </div>
            <div class="col-md-1">
            <img class="footer_img" src="static/img/SUA_logo.png">

            </div>
            <div class="col-md-1">
            <img class="footer_img" src="static/img/SUZA_Logo.png">

            </div>
            <div class="col-md-1">
            <img class="footer_img" src="static/img/UDSM_logo.png">

            </div>
            <div class="col-md-1 ">
            <img class="footer_img1" src="static/img/UTU.png">

            </div>
        </div>
      </div>

my_geonode/templates/geonode_base.html
{% extends "site_base.html" %}

{% load i18n %}
{% load staticfiles %}

my_geonode/templates/layers/layer_base.html
{% extends "geonode_base.html" %}
{% load i18n %}
{% block extra_head %}
      <link href="{{ STATIC_URL }}css/site_base.css" rel="stylesheet"/>
{% endblock %}
{% block title %} {{ block.super }} {% endblock %}
{% block header %}
    {% include 'navigation.html' %}
{% endblock header %}

{% block body_class %}{% trans "data" %}{% endblock body_class %}

{% block body_outer %}
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

my_geonode/templates/layers/layer_change_poc.html
{% extends "admin/base_site.html" %}

{% load i18n %}
	
{% block breadcrumbs %}<div class="breadcrumbs"><a href="/">{% trans "Home" %}</a> &rsaquo; {% trans "Change point of contact" %}</div>{% endblock %}
	
{% block title %}{% trans 'Change point of contact' %}{% endblock %}

{% block content %}
<h3>{% trans "Assign a new point of contact to the layers below:" %}</h3>
{% for layer in layers %}
<li>{{ layer }}</li>
{% endfor %}
<form method="POST">
{% csrf_token %}	
{{ form.as_p }}
 <p><input type="submit" value="{% trans "Submit" %}" /></p>
</form>
<ul>

{% endblock %}
</ul>

my_geonode/templates/layers/layer_granule_remove.html
{% extends "layers/layer_base.html" %}
{% load i18n %}

{% block title %}{{ layer.alternate }} — {{ block.super }}{% endblock %}

{% block body %}
<div class="page-header">
  <a href="{% url "layer_browse" %}?limit={{ CLIENT_RESULTS_LIMIT }}" class="btn btn-primary pull-right">{% trans "Explore Layers" %}</a>
  <h2 class="page-title">{% trans "Remove Mosaic Granules" %}</h2>
</div>
<div class="row">
  <div class="col-md-8">
    <p class="lead">
        {% blocktrans with layer.alternate as layer_title %}
          Are you sure you want to remove Granule {{ granule_id }} of the Mosaic <a href="{{ layer.get_absolute_url }}">{{ layer_title }}</a>?
        {% endblocktrans %}
      </p>
    <form action="{% url "layer_granule_remove" granule_id layer.service_typename %}" method="POST">
      {% csrf_token %}
      <input type="hidden" value="{{ layer.service_typename }}" />
      <div class="form-actions">
        <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger" />
        <a href="{{ layer.get_absolute_url }}" class="btn btn-default">{% trans "No, don't remove it" %}</a>
      </div>
    </form>
  </div>
  {% if layer.maps %}
    <div class="col-md-4">
    <ul class="nav nav-list">
    <li class="nav-header">{% trans "This action affects the following maps:" %}</li>
    {% for map_layer in layer.maps %}
      <li><a href="{{ map_layer.map.get_absolute_url }}">{{ map_layer.map.title }}</a></li>
    {% empty %}
      <li>{% trans "No maps are using this layer" %}</li>
    {% endfor %}
    </ul>
    </div>
  {% endif %}
</div>
{% endblock %}

my_geonode/templates/layers/layer_list.html
{% extends "layers/layer_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %} {% trans "Explore Layers" %} - {{ block.super }} {% endblock %}

{% block body_class %}layers explore{% endblock %}

{% block body %}
<div class="page-header">
  <a href="{% url "layer_upload" %}" class="btn btn-primary pull-right">{% trans "Upload Layers" %}</a>
  <h2 class="page-title">{% trans "Explore Layers" %}</h2>
</div>
  {% with include_type_filter='true' %}
  {% with header='Type' %}
  {% with filter='type__in' %}
  {% include "search/_search_content.html" %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% include "_bulk_permissions_form.html" %}
{% endblock %}

{% block extra_script %}
{{ block.super }}
  {% if GEONODE_SECURITY_ENABLED %}
    {% include "_permissions_form_js.html" %}
  {% endif %}
  <script type="text/javascript">
      {% if HAYSTACK_SEARCH %}
          SEARCH_URL = '{% url 'api_get_search' api_name='api' resource_name='base' %}?type__in=layer'
      {% else %}
          SEARCH_URL = '{% url 'api_dispatch_list' api_name='api' resource_name='layers' %}';
      {% endif %}
    FILTER_TYPE = 'layer';
  </script>
  {% with include_spatial='true' %}
  {% include 'search/search_scripts.html' %}
  {% endwith %}
{% endblock extra_script %}

my_geonode/templates/layers/layer_metadata.html
{% extends "metadata_base.html" %}
{% load i18n %}
{% load bootstrap_tags %}
{% load base_tags %}
{% load guardian_tags %}
{% load floppyforms %}

{% block title %}{{ layer.alternate }} — {{ block.super }}{% endblock title %}

{% block head %}
    {% include "ol/layers/layer_ol2_map.html" %}
{{ block.super }}
{% endblock head %}

{% block body_class %}{% trans "data" %}{% endblock body_class %}

{% block body_outer %}
<div class="container-fluid page-header" style="position: relative;">
  <h2 class="page-title">{% trans "Metadata" %}&nbsp;{% blocktrans with layer.title as layer_title %}for {{ layer_title }}{% endblocktrans %}</h2>
      <div id="profileCompleteness" class="alert alert-info" style="position: absolute; right: 0; top: 0; padding: 4px;">
        <strong>{% trans "Completeness" %}</strong>
        <div style="padding: 2px;">
          <small class="completed text-success" style="display: none; "><i class="fa fa-check"></i>{% trans "Metadata Schema mandatory fields completed" %}</small>
          <small class="not-completed text-danger" style="display: none; "><i class="fa fa-remove"></i>{% trans "Check Schema mandatory fields" %}</small>
        </div>
        <div class="progress" style="margin-bottom:2px;">
        <div class="progress-bar progress-bar-striped" role="progress-bar" >
          70%
        </div>
        </div>
      </div>
  </h2>
</div>

    <form id="metadata_update" class="form-horizontal" action="{% url "layer_metadata" layer.service_typename %}" method="POST">
      {% if layer.metadata_uploaded_preserve %}
        <p class="bg-warning">{% blocktrans %}Note: this layer's orginal metadata was populated and preserved by importing a metadata XML file.
          This metadata cannot be edited.{% endblocktrans %}</p>
      {% elif layer.metadata_uploaded %}
        <p class="bg-warning">{% blocktrans %}Note: this layer's orginal metadata was populated by importing a metadata XML file.
          GeoNode's metadata import supports a subset of ISO, FGDC, and Dublin Core metadata elements.
          Some of your original metadata may have been lost.{% endblocktrans %}</p>
      {% endif %}

      {% if layer_form.errors or attribute_form.errors or category_form.errors or author_form.errors or poc.errors %}
    	  <p class="bg-danger">{% blocktrans %}Error updating metadata.  Please check the following fields: {% endblocktrans %}</p>
          <ul class="bg-danger">
          {% if author_form.errors %}
            <li>{% trans "Metadata Author" %}</li>
            {{ author_form.errors }}
          {% endif %}
          {% if poc_form.errors %}
            <li>{% trans "Point of Contact" %}</li>
            {{ poc_form.errors }}
          {% endif %}
          {% for field in layer_form %}
            {% if field.errors %}
            <li>{{ field.label }}</li>
            {% endif %}
          {% endfor %}
          {% if not attribute_form.is_valid %}
            <li>{% trans "Attributes" %}</li>
            {% for field in attribute_form %}
            {% if field.errors %}
            <li>{{ field.errors }}</li>
            {% endif %}
            {% endfor %}
          {% endif %}
          {% if category_form.errors %}
            <li>{{ category_form.errors.as_ul }}</li>
          {% endif %}
          </ul>
        {% endif %}

        {% csrf_token %}
        <div id="mdeditor_form" class="col-md-12 form-controls">
          {% form layer_form using "layouts/panels.html" %}
          {# layer_form|as_bootstrap #}
        </div>

        <div class="row">
          <div class="col-md-12 grid-spacer">
            <fieldset class="form-controls modal-forms modal hide fade" id="poc_form" >
              <h2>{% trans "Point of Contact" %}</h2>
              {{ poc_form|as_bootstrap }}
              <button type='button' class="modal-cloose-btn btn btn-primary">{% trans "Done" %}</button>
            </fieldset>
            <fieldset class="form-controls modal-forms modal hide fade" id="metadata_form">
              <h2>{% trans "Metadata Provider" %}</h2>
                {{ author_form|as_bootstrap }}
              <button type='button' class="modal-cloose-btn btn btn-primary">{% trans "Done" %}</button>
            </fieldset>

            {% if not layer.metadata_uploaded_preserve %}
            <div class="form-actions">
              <a href="{% url 'layer_detail' layername=resource.alternate %}" class="btn btn-primary">{% trans "Return to Layer" %}</a>
              <input type="button" id="btn_back_dwn" class="btn btn-primary" style="display: none" value="{% trans "<< Back" %}"/>
              <input type="submit" id="btn_upd_md_dwn" class="btn btn-primary" value="{% trans "Update" %}"/>
              <input type="button" id="btn_next_dwn" class="btn btn-primary" value="{% trans "Next >>" %}"/>
            </div>
            {% endif %}
          </div>
        </div>
      </form>

{{ block.super }}
{% endblock body_outer %}

my_geonode/templates/layers/layer_metadata_advanced.html
{% extends "metadata_base.html" %}
{% load i18n %}
{% load bootstrap_tags %}
{% load base_tags %}
{% load guardian_tags %}

{% block title %}{{ layer.alternate }} — {{ block.super }}{% endblock %}

{% block body_class %}{% trans "data" %}{% endblock %}

{% block body_outer %}

{{ block.super }}

<div class="page-header">
  <a href="{% url "layer_browse" %}?limit={{ CLIENT_RESULTS_LIMIT }}" class="btn btn-primary pull-right">{% trans "Explore Layers" %}</a>
  <h2 class="page-title">{% trans "Edit Metadata" %}</h2>
</div>
<div class="row">
  <div class="col-md-8">
    <p class="lead">
      {% blocktrans with layer.alternate as layer_title %}
        Editing details for {{ layer_title }}
      {% endblocktrans %}
    </p>
    <form id="metadata_update" class="form-horizontal" action="{% url "layer_metadata" layer.service_typename %}" method="POST">
      {% if layer.metadata_uploaded_preserve %}
        <p class="bg-warning">{% blocktrans %}Note: this layer's orginal metadata was populated and preserved by importing a metadata XML file.
          This metadata cannot be edited.{% endblocktrans %}</p>
      {% elif layer.metadata_uploaded %}
        <p class="bg-warning">{% blocktrans %}Note: this layer's orginal metadata was populated by importing a metadata XML file.
          GeoNode's metadata import supports a subset of ISO, FGDC, and Dublin Core metadata elements.
          Some of your original metadata may have been lost.{% endblocktrans %}</p>
      {% endif %}

      {% if layer_form.errors or attribute_form.errors or category_form.errors or author_form.errors or poc.errors %}
    	  <p class="bg-danger">{% blocktrans %}Error updating metadata.  Please check the following fields: {% endblocktrans %}</p>
          <ul class="bg-danger">
          {% if author_form.errors %}
            <li>{% trans "Metadata Author" %}</li>
            {{ author_form.errors }}
          {% endif %}
          {% if poc_form.errors %}
            <li>{% trans "Point of Contact" %}</li>
            {{ poc_form.errors }}
          {% endif %}
          {% for field in layer_form %}
            {% if field.errors %}
            <li>{{ field.label }}</li>
            {% endif %}
          {% endfor %}
          {% if not attribute_form.is_valid %}
            <li>{% trans "Attributes" %}</li>
            {% for field in attribute_form %}
            {% if field.errors %}
            <li>{{ field.errors }}</li>
            {% endif %}
            {% endfor %}
          {% endif %}
          {% if category_form.errors %}
            <li>{{ category_form.errors.as_ul }}</li>
          {% endif %}
          </ul>
        {% endif %}

        {% if not layer.metadata_uploaded_preserve %}
        <div class="form-actions">
          <a href="{% url 'layer_detail' layername=resource.alternate %}" class="btn btn-primary">{% trans "Return to Layer" %}</a>
          <input type="submit" id="btn_upd_md_up" class="btn btn-primary" value="{% trans "Update" %}"/>
        </div>
        {% endif %}

        {% csrf_token %}
        <div class="col-md-6 form-controls">
          {{ layer_form|as_bootstrap }}
        </div>
        <div class="row">
          <div class="col-md-12">
            <label class="control-label required-field">{% trans "Category" %}</label>
            <fieldset id="category_form">
              {% autoescape off %}
              {% for choice in category_form.category_choice_field.field.choices %}
              <div class="col-md-6">
                <label class="fancy-checkbox">
                    <input type="radio" name="category_choice_field" value="{{ choice.0 }}"
                      {% ifequal category_form.initial choice.0 %} checked="checked" {% endifequal %} />
                    {{ choice.1 }}
                </label>
              </div>
              <!-- div class="radio col-md-6">
                <input type="radio" name="category_choice_field" value="{{ choice.0 }}"
                  {% ifequal category_form.initial choice.0 %} checked="checked" {% endifequal %}>
                  {{ choice.1 }}
                </input>
              </div -->
              {% endfor %}
              {% endautoescape %}
            </fieldset>
          </div>

          <div class="col-md-12 grid-spacer">
            <h5>{% trans "Attributes" %}</h5>
            {{ attribute_form.management_form }}
            <table class="table table-striped table-bordered table-condensed">
              <tr>
                <th>{% trans "Attribute" %}</th>
                <th>{% trans "Label" %}</th>
                <th>{% trans "Description" %}</th>
                <th>{% trans "Display Order" %}</th>
              </tr>
              {% for form in attribute_form.forms %}
              {% if form.attribute %}
              <tr>
                <td><div style="display:none">{{form.id}}</div>{{form.attribute}}</td>
                <td>{{form.attribute_label}}</td>
                <td>{{form.description}}</td>
                <td>{{form.display_order}}</td>
              </tr>
              {% endif %}
              {% endfor %}
            </table>

            <fieldset class="form-controls modal-forms modal hide fade" id="poc_form" >
              <h2>{% trans "Point of Contact" %}</h2>
              {{ poc_form|as_bootstrap }}
              <button type='button' class="modal-cloose-btn btn btn-primary">{% trans "Done" %}</button>
            </fieldset>
            <fieldset class="form-controls modal-forms modal hide fade" id="metadata_form">
              <h2>{% trans "Metadata Provider" %}</h2>
                {{ author_form|as_bootstrap }}
              <button type='button' class="modal-cloose-btn btn btn-primary">{% trans "Done" %}</button>
            </fieldset>

            {% if not layer.metadata_uploaded_preserve %}
            <div class="form-actions">
              <a href="{% url 'layer_detail' layername=resource.alternate %}" class="btn btn-primary">{% trans "Return to Layer" %}</a>
              <input type="submit" id="btn_upd_md_dwn" class="btn btn-primary" value="{% trans "Update" %}"/>
            </div>
            {% endif %}
          </div>
        </div>
      </form>
  </div>
</div>
{% endblock %}

my_geonode/templates/layers/layer_metadata_detail.html
{% extends "metadata_detail.html" %}

my_geonode/templates/layers/layer_metadata_upload.html
{% extends "upload/layer_upload_metadata_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load bootstrap_tags %}
{% load pagination_tags %}
{% load base_tags %}
{% load guardian_tags %}

{% block title %} {% trans "Upload Layer Metadata"  %} - {{ block.super }}  {% endblock %}

{% block body_class %}{% trans "layers upload" %}{% endblock %}


{% block head %}

{{ block.super }}
{% endblock %}

{% block body_outer %}

<div class="page-header">
  <a href="{% url "layer_browse" %}?limit={{ CLIENT_RESULTS_LIMIT }}" class="btn btn-primary pull-right" style="margin-left: 3px;">{% trans "Explore Layers" %}</a>
  <a href="{% url 'layer_detail' layername=resource.alternate %}" class="btn btn-primary pull-right" style="margin-left: 3px;">{% trans "Return to Layer" %}</a>
  <h2 class="page-title">{% trans "Upload Layer Metadata" %} <small>{% trans "(XML - ISO, FGDC, ebRIM, Dublin Core)" %}<small></h2>
</div>

<div class="row">
  <div class="col-md-8">
    {% if incomplete %}
    <section class="widget" id="incomplete-download-list">
      <h3>{% trans "Incomplete Uploads" %}</h3>
      <p>{% trans "You have the following incomplete uploads" %}:</p>
      {% for u in incomplete %}
      <div class="clearfix uip" id="incomplete-{{ u.import_id }}">
        <div class="pull-left">{{ u.name }}, {% trans "last updated on" %} {{ u.date }}</div>
        <div class="upload_actions pull-right">
          <a class="btn btn-mini" href="#" id="resume-{{ u.import_id }}">{% trans "Resume" %}</a>
          <a class="btn btn-mini" href="#" id="delete-{{ u.import_id }}"><i class="icon-trash"></i> {% trans "Delete" %}</a>
        </div>
      </div>
      {% endfor %}
    </section>
    <div id="confirm-delete" class="hidden alert alert-warning">
      {% trans "Are you sure you want to delete this upload?" %}
      <a href="#y" class="btn btn-danger">{% trans "Delete" %}</a>
      <a href="#n" class="btn btn-default">{% trans "Cancel" %}</a>
      <a href="#yy">{% trans "Delete, and don't ask me again." %}</a>
    </div>
    {% endif %}

    {% block additional_info %}{% endblock %}

    {% if errors %}
    <div id="errors" class="alert alert-danger">
      {% for error in errors %}
      <p>{{ error }}</p>
      {% endfor %}
    </div>
    {% endif %}

    <div id="upload-status"></div>

    <section id="drop-zone">
      <h3><i class="fa fa-cloud-upload"></i><br />{% trans "Drop files here" %}</h3>
    </section>

    <p>{% trans " or select them one by one:" %}</p>

    <form id="file-uploader" method="post" enctype="multipart/form-data">
      <!-- UI change to hide the list of previously uploaded files from the user -->
      <input type="file" id="file-input" style="display: none;" multiple>
      <input class="btn btn-default" type="button" value="{% trans "Choose Files" %}" onclick="document.getElementById('file-input').click();">
    </form>

    <section class="widget">
      <ul id="global-errors"></ul>
      <h4>{% trans "Files to be uploaded" %}</h4>
      <div id="file-queue"></div>
      <div class="checkbox" style="display:none;" id="metadata_upload_form_check">
          {% trans "Is Upload Metadata XML Form" %} <input type="checkbox" name="metadata_upload_form" id="id_metadata_upload_form" checked="true"/>
          <input type="text" name="layer_title" id="id_layer_title" value="{{ resource.alternate }}"/>
      </div>
    </section>

    <section>
      <a href="{% url "layer_metadata_upload" resource.alternate %}" id="clear-button" class="btn btn-default">{% trans "Clear" %}</a>
      <a href="#" id="upload-button" class="btn btn-danger">{% trans "Upload files" %}</a>
    </section>
  </div>

  {% if GEOSERVER_BASE_URL %}
    {% get_obj_perms request.user for resource.layer as "layer_perms" %}
  {% endif %}

  {% if GEONODE_SECURITY_ENABLED %}
  {% if "change_resourcebase_permissions" in perms_list %}
  <li class="list-group-item">
    <h4>{% trans "Permissions" %}</h4>
    <p>{% trans "Click the button below to change the permissions of this layer." %}</p>
    <p><a href="#modal_perms" data-toggle="modal" class="btn btn-primary btn-block" data-target="#_permissions">{% trans "Change Layer Permissions" %}</a></p>
  </li>
  {% endif %}
  {% endif %}

  {% if GEONODE_SECURITY_ENABLED %}
  <div class="col-md-4">
    <h3>{% trans "Permissions"  %}</h3>
    <form id="permission_form">
      {% include "_permissions.html" %}
    </form>
  </div>
  {% endif %}

</div>
{% endblock %}


{% block extra_script %}
    {{ block.super }}
    <script data-main="{% static 'geonode/js/upload/main' %}"
      src="{% static 'lib/js/require.js' %}">
    </script>
    <script type="text/javascript">
    {% autoescape off %}

      csrf_token =  "{{ csrf_token }}",
      form_target = "{{ LAYER_ANCILLARY_FILES_UPLOAD_URL }}",
      time_enabled = false,
      mosaic_enabled = false,
      userLookup = "{% url "account_ajax_lookup" %}"

    {% endautoescape %}

    </script>
    {% if GEONODE_SECURITY_ENABLED %}
        {% with resource=layer %}
            {% include "_permissions_form_js.html" %}
        {% endwith %}
    {% endif %}
{% endblock extra_script %}

my_geonode/templates/layers/layer_style_edit.html
{% extends "layers/layer_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load bootstrap_tags %}
{% load pagination_tags %}
{% load base_tags %}
{% load guardian_tags %}
{% load client_lib_tags %}

{% block title %}{{ resource.title|default:resource.alternate }} — {{ block.super }}{% endblock %}

{% block head %}
  {% if TWITTER_CARD %}
    {% include "base/_resourcebase_twittercard.html" %}
  {% endif %}

  {% if OPENGRAPH_ENABLED %}
    {% include "base/_resourcebase_opengraph.html" %}
  {% endif %}

  {% get_layer_style_edit %}
{{ block.super }}
{% endblock %}

{% block body_class %}{% trans "layers" %}{% endblock %}

polls/templates/polls/detail.html
{% extends 'site_base.html' %}
{% block body %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'site_base.html' %}
{% block body %}
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>


    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'site_base.html' %}
{% block body %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}